apiVersion: apps/v1
kind: Deployment
metadata:
  name: practify
  namespace: practify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practify
  template:
    metadata:
      labels:
        app: practify
    spec:
      imagePullSecrets:
        - name: dockerhub-key
      containers:
        - name: practify
          image: moindev/practify:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: practify-secrets
          env:
            - name: RAILS_ENV
              value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: practify-service
  namespace: practify
spec:
  selector:
    app: practify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practify-ingress
  namespace: practify
  annotations:
    # Forces Traefik to use the websecure (HTTPS) entrypoint
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # Tells Traefik that this specific route REQUIRES TLS
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - rpi02.taila27a53.ts.net    
    secretName: practify-tls-cert
  - hosts:
    - practify.co.in    
    secretName: practify-letsencrypt-cert
  rules:
  - host: rpi02.taila27a53.ts.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: practify-service
            port:
              number: 80
  - host: practify.co.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: practify-service
            port:
              number: 80