apiVersion: v1
kind: ConfigMap
metadata:
  name: practify-hosts-config
  namespace: practify
data:
  zz_hosts.rb: |
    Rails.application.config.hosts << "practify.co.in"
    Rails.application.config.hosts << "www.practify.co.in"
    Rails.application.config.hosts << "rpi02.taila27a53.ts.net"
    Rails.application.config.assume_ssl = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: practify
  namespace: practify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practify
  template:
    metadata:
      labels:
        app: practify
    spec:
      imagePullSecrets:
        - name: dockerhub-key
      containers:
        - name: practify
          image: moindev/practify:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: practify-secrets
          env:
            - name: RAILS_ENV
              value: "production"
            - name: SMTP_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: SMTP_ADDRESS
            - name: SMTP_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: SMTP_USER_NAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: SMTP_PASSWORD
          volumeMounts:
            - name: hosts-config
              mountPath: /rails/config/initializers/zz_hosts.rb
              subPath: zz_hosts.rb
              readOnly: true
      volumes:
        - name: hosts-config
          configMap:
            name: practify-hosts-config
---
apiVersion: v1
kind: Service
metadata:
  name: practify-service
  namespace: practify
spec:
  selector:
    app: practify
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practify-ingress
  namespace: practify
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: practify.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: practify-service
                port:
                  number: 80
    - host: www.practify.co.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: practify-service
                port:
                  number: 80
